name: SR_Env
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - pygame=2.5.2
  - gymnasium=1.0.0
  - numpy=1.26.4
  - pettingzoo=1.24.3
  - pip
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - scipy=1.15.2
  - stable-baselines3=2.6.0
  - pip:
      - supersuit==3.9.3
