name: seniorresearch
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.10
  - aiosignal=1.3.1
  - attrs=24.2.0
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.77
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - farama-notifications=0.0.4
  - filelock=3.16.1
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - gymnasium=0.29.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - intel-openmp=2024.2.1
  - jax-jumpy=1.0.0
  - jinja2=3.1.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libexpat=2.6.3
  - libffi=3.4.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libsqlite=3.46.1
  - libuv=1.49.1
  - libxml2=2.12.7
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.1
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - networkx=3.4.1
  - numpy=1.26.4
  - openssl=3.3.2
  - pip=24.2
  - propcache=0.2.0
  - psutil=6.0.0
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pyg=2.6.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.4
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - scipy=1.14.1
  - setuptools=75.1.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.14.0
  - zstandard=0.23.0
  - zstd=1.5.6
